package services;
// Generated 22/Mai/2012 20:37:29 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Dservices generated by hbm2java
 */
public class Dservices  implements java.io.Serializable {


     private int id;
     private String name;
     private String address;
     private String zipCode1;
     private String zipCode2;
     private String zipDesignation;
     private String phone1;
     private String phone2;
     private String fax;
     private String email;
     private String responsible;
     private String status;
     private Date creationDate;
     private Date updateDate;

    public Dservices() {
    }

    public Dservices(int id, String name, String address, String zipCode1, String zipCode2, String zipDesignation, String phone1, String phone2, String fax, String email, String responsible, String status, Date creationDate, Date updateDate) {
       this.id = id;
       this.name = name;
       this.address = address;
       this.zipCode1 = zipCode1;
       this.zipCode2 = zipCode2;
       this.zipDesignation = zipDesignation;
       this.phone1 = phone1;
       this.phone2 = phone2;
       this.fax = fax;
       this.email = email;
       this.responsible = responsible;
       this.status = status;
       this.creationDate = creationDate;
       this.updateDate = updateDate;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getZipCode1() {
        return this.zipCode1;
    }
    
    public void setZipCode1(String zipCode1) {
        this.zipCode1 = zipCode1;
    }
    public String getZipCode2() {
        return this.zipCode2;
    }
    
    public void setZipCode2(String zipCode2) {
        this.zipCode2 = zipCode2;
    }
    public String getZipDesignation() {
        return this.zipDesignation;
    }
    
    public void setZipDesignation(String zipDesignation) {
        this.zipDesignation = zipDesignation;
    }
    public String getPhone1() {
        return this.phone1;
    }
    
    public void setPhone1(String phone1) {
        this.phone1 = phone1;
    }
    public String getPhone2() {
        return this.phone2;
    }
    
    public void setPhone2(String phone2) {
        this.phone2 = phone2;
    }
    public String getFax() {
        return this.fax;
    }
    
    public void setFax(String fax) {
        this.fax = fax;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getResponsible() {
        return this.responsible;
    }
    
    public void setResponsible(String responsible) {
        this.responsible = responsible;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Date getCreationDate() {
        return this.creationDate;
    }
    
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }
    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }




}


